const PDFDocument = require("pdfkit");

const Mission = require("../models/Mission");
const Diver = require("../models/Diver");
const Telemetry = require("../models/Telemetry");
const DiveEvent = require("../models/DiveEvent");
const Emergency = require("../models/Emergency");

const generateMissionReport = async (req, res) => {
  try {
    const { missionId } = req.params;

    const mission = await Mission.findById(missionId);

    if (!mission) {
      return res.status(404).json({
        message: "Mission not found",
      });
    }

    const divers = await Diver.find({ missionId });

    const telemetry = await Telemetry.find({ missionId });

    const events = await DiveEvent.find({ missionId })
      .populate("diverId", "name")
      .sort({ timestamp: 1 });

    const emergencies = await Emergency.find({ missionId })
      .populate("diverId", "name")
      .sort({ triggeredAt: 1 });

    const maximumDepth =
      telemetry.length > 0
        ? Math.max(...telemetry.map((item) => item.depth))
        : 0;

    const averageHeartRate =
      telemetry.length > 0
        ? Math.round(
            telemetry.reduce(
              (sum, item) => sum + item.heartRate,
              0
            ) / telemetry.length
          )
        : 0;

    const averageOxygen =
      telemetry.length > 0
        ? Number(
            (
              telemetry.reduce(
                (sum, item) => sum + item.oxygenSaturation,
                0
              ) / telemetry.length
            ).toFixed(1)
          )
        : 0;

    const doc = new PDFDocument({
      margin: 50,
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="DiveQ-${mission.missionName.replace(
        /\s+/g,
        "-"
      )}-Report.pdf"`
    );

    doc.pipe(res);

    // Title
    doc
      .fontSize(24)
      .text("DiveQ Mission Report", {
        align: "center",
      });

    doc.moveDown();

    doc
      .fontSize(18)
      .text(mission.missionName);

    doc.moveDown();

    // Mission Details
    doc.fontSize(14).text("Mission Details");
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Location: ${mission.location}`);
    doc.text(`Water Body: ${mission.waterBody}`);
    doc.text(`Mission Type: ${mission.missionType}`);
    doc.text(`Status: ${mission.status}`);
    doc.text(
      `Mission Date: ${new Date(
        mission.missionDate
      ).toLocaleDateString()}`
    );

    doc.moveDown();

    // Analytics
    doc.fontSize(14).text("Mission Analytics");
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Divers: ${divers.length}`);
    doc.text(`Telemetry Records: ${telemetry.length}`);
    doc.text(`Dive Events: ${events.length}`);
    doc.text(`Emergency Events: ${emergencies.length}`);
    doc.text(`Maximum Depth: ${maximumDepth} m`);
    doc.text(`Average Heart Rate: ${averageHeartRate} bpm`);
    doc.text(
      `Average Oxygen Saturation: ${averageOxygen}%`
    );

    doc.moveDown();

    // Diver Details
    doc.fontSize(14).text("Divers");
    doc.moveDown(0.5);

    doc.fontSize(11);

    if (divers.length === 0) {
      doc.text("No divers assigned.");
    } else {
      divers.forEach((diver, index) => {
        doc.text(
          `${index + 1}. ${diver.name} — ${diver.certification}`
        );
      });
    }

    doc.moveDown();

    // Emergency History
    doc.fontSize(14).text("Emergency History");
    doc.moveDown(0.5);

    doc.fontSize(11);

    if (emergencies.length === 0) {
      doc.text("No emergency events recorded.");
    } else {
      emergencies.forEach((emergency, index) => {
        doc.text(
          `${index + 1}. ${
            emergency.diverId?.name || "Unknown Diver"
          } — ${emergency.action} — ${
            emergency.status
          }`
        );
      });
    }

    doc.moveDown();

    // Dive Events
    doc.fontSize(14).text("Dive Timeline");
    doc.moveDown(0.5);

    doc.fontSize(11);

    if (events.length === 0) {
      doc.text("No dive events recorded.");
    } else {
      events.forEach((event, index) => {
        doc.text(
          `${index + 1}. ${
            event.title
          } — ${event.diverId?.name || "Unknown Diver"}`
        );

        if (event.description) {
          doc.text(`   ${event.description}`);
        }
      });
    }

    doc.moveDown(2);

    doc
      .fontSize(9)
      .text(
        "Generated by DiveQ AI-Powered Dive Command Center",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.error(
      "Generate mission report error:",
      error.message
    );

    res.status(500).json({
      message: "Failed to generate mission report",
      error: error.message,
    });
  }
};

module.exports = {
  generateMissionReport,
};